//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoArquitectura_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCuerpoUsuario
    {
        public int DetalleCuerpoID { get; set; }
        public decimal Peso { get; set; }
        public decimal Altura { get; set; }
        public decimal PorcentajeMasaMuscular { get; set; }
        public decimal PorcentajeGrasaCorporal { get; set; }
    }
}
