//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoArquitectura_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menbresia
    {
        public int MenbresiaID { get; set; }
        public int TipoMembresiaID { get; set; }
        public int TipoEstadoID { get; set; }
        public System.DateTime FechaAdquisicion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public int UsuarioID { get; set; }
    }
}
