//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoArquitectura_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoRol
    {
        public int TipoRol_ID { get; set; }
        public string NombreRol { get; set; }
        public string Descripcion { get; set; }
    }
}
